#:import MDBoxLayout kivymd.uix.boxlayout.MDBoxLayout
#:import MDCard kivymd.uix.card.MDCard
#:import MDLabel kivymd.uix.label.MDLabel
#:import MDRaisedButton kivymd.uix.button.MDRaisedButton
#:import MDTextField kivymd.uix.textfield.MDTextField
#:import MDIconButton kivymd.uix.button.MDIconButton

<MainScreen>:
    MDBoxLayout:
        orientation: 'vertical'
        spacing: dp(10)
        padding: dp(10)

        MDBoxLayout:
            adaptive_height: True
            spacing: dp(10)

            MDTextField:
                id: name_input
                hint_text: "Nom de l'item"
                size_hint_x: 0.4

            MDTextField:
                id: desc_input
                hint_text: "Description"
                size_hint_x: 0.4

            MDRaisedButton:
                text: "Ajouter"
                size_hint_x: 0.2
                on_release: 
                    app.controller.add_item(name_input.text, desc_input.text, "assets/logo.png")
                    name_input.text = ""
                    desc_input.text = ""

        MDLabel:
            text: "Mes Items"
            halign: "center"
            font_style: "H5"
            adaptive_height: True
            theme_text_color: "Primary"

        ScrollView:
            GridLayout:
                id: list_container
                cols: 2
                spacing: dp(15)
                padding: dp(10)
                size_hint_y: None
                height: self.minimum_height

<ItemCard@MDCard>:
    orientation: 'vertical'
    size_hint_y: None
    height: "240dp"
    padding: "10dp"
    spacing: "10dp"
    elevation: 2
    
    AsyncImage:
        source: root.source
        size_hint_y: 0.6
        allow_stretch: True
        keep_ratio: True
    
    MDLabel:
        text: root.name
        halign: "center"
        font_style: "Subtitle1"
        bold: True
        size_hint_y: 0.2
        text_size: self.width, None
    
    MDLabel:
        text: root.desc
        halign: "center" 
        font_style: "Body2"
        theme_text_color: "Secondary"
        size_hint_y: 0.2
        text_size: self.width, None
